version: "3.9"

services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    volumes:
      - .:/app
    environment:
      SERVER_ADDR: ":3010"
      SERVICE_NAME: "api-gateway"
      URL_SHORTENER_URL: "http://server:3011"
      LOG_LEVEL: "0"
      APP_ENV: "local"
      ENABLE_X_CORRELATION_ID: "1"
    networks:
      - sturl-net

networks:
  sturl-net:
    external: true
