version: "3.9"

services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    volumes:
      - .:/app
    environment:
      SERVER_ADDR: ":3010"
      SERVICE_NAME: "api-gateway"
      URL_SHORTENER_SERVICE_NAME: "url-shortener"
      URL_SHORTENER_URL: "http://server:3011"
      LOG_LEVEL: "0"
      APP_ENV: "local"
      ENABLE_X_CORRELATION_ID: "1"
      OTEL_EXPORTER_OTLP_ENDPOINT: "jaeger:4317"
    networks:
      - sturl-net

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "16686:16686"   # Web UI
      - "4317:4317"     # OTLP gRPC endpoint (OpenTelemetry)
    environment:
      - COLLECTOR_OTLP_ENABLED:true
    networks:
      - sturl-net

networks:
  sturl-net:
    external: true
