// Code generated by mockery v2.53.4. DO NOT EDIT.

package shorturl

import (
	context "context"

	model "github.com/kytruongdev/sturl/url-shortener-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockController is an autogenerated mock type for the Controller type
type MockController struct {
	mock.Mock
}

// CrawlURLMetadata provides a mock function with given fields: ctx, shortCode
func (_m *MockController) CrawlURLMetadata(ctx context.Context, shortCode string) (model.UrlMetadata, error) {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for CrawlURLMetadata")
	}

	var r0 model.UrlMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.UrlMetadata, error)); ok {
		return rf(ctx, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.UrlMetadata); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(model.UrlMetadata)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Retrieve provides a mock function with given fields: _a0, _a1
func (_m *MockController) Retrieve(_a0 context.Context, _a1 string) (model.ShortUrl, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 model.ShortUrl
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.ShortUrl, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.ShortUrl); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.ShortUrl)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Shorten provides a mock function with given fields: _a0, _a1
func (_m *MockController) Shorten(_a0 context.Context, _a1 ShortenInput) (model.ShortUrl, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Shorten")
	}

	var r0 model.ShortUrl
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ShortenInput) (model.ShortUrl, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ShortenInput) model.ShortUrl); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.ShortUrl)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ShortenInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockController creates a new instance of MockController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockController {
	mock := &MockController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
