output = "internal/repository/orm"
pkgname = "orm"
wipe = true
add-global-variants = false

[psql]
  dbname = "url-shortener"
  host = "localhost"
  port = 5432
  user = "postgres"
  pass = "postgres"
  sslmode = "disable"
  blacklist = ["schema_migrations"]
