// Code generated by mockery v2.53.4. DO NOT EDIT.

package orm

import (
	context "context"

	boil "github.com/aarondl/sqlboiler/v4/boil"

	mock "github.com/stretchr/testify/mock"
)

// MockOutgoingEventHook is an autogenerated mock type for the OutgoingEventHook type
type MockOutgoingEventHook struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockOutgoingEventHook) Execute(_a0 context.Context, _a1 boil.ContextExecutor, _a2 *OutgoingEvent) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, boil.ContextExecutor, *OutgoingEvent) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockOutgoingEventHook creates a new instance of MockOutgoingEventHook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutgoingEventHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutgoingEventHook {
	mock := &MockOutgoingEventHook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
