// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// OutgoingEvent is an object representing the database table.
type OutgoingEvent struct {
	ID            int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Payload       types.JSON  `boil:"payload" json:"payload" toml:"payload" yaml:"payload"`
	Topic         string      `boil:"topic" json:"topic" toml:"topic" yaml:"topic"`
	Status        string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	LastError     null.String `boil:"last_error" json:"last_error,omitempty" toml:"last_error" yaml:"last_error,omitempty"`
	CorrelationID string      `boil:"correlation_id" json:"correlation_id" toml:"correlation_id" yaml:"correlation_id"`
	TraceID       string      `boil:"trace_id" json:"trace_id" toml:"trace_id" yaml:"trace_id"`
	SpanID        string      `boil:"span_id" json:"span_id" toml:"span_id" yaml:"span_id"`
	RetryCount    int         `boil:"retry_count" json:"retry_count" toml:"retry_count" yaml:"retry_count"`
	CreatedAt     time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *outgoingEventR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L outgoingEventL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var OutgoingEventColumns = struct {
	ID            string
	Payload       string
	Topic         string
	Status        string
	LastError     string
	CorrelationID string
	TraceID       string
	SpanID        string
	RetryCount    string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "id",
	Payload:       "payload",
	Topic:         "topic",
	Status:        "status",
	LastError:     "last_error",
	CorrelationID: "correlation_id",
	TraceID:       "trace_id",
	SpanID:        "span_id",
	RetryCount:    "retry_count",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

var OutgoingEventTableColumns = struct {
	ID            string
	Payload       string
	Topic         string
	Status        string
	LastError     string
	CorrelationID string
	TraceID       string
	SpanID        string
	RetryCount    string
	CreatedAt     string
	UpdatedAt     string
}{
	ID:            "outgoing_events.id",
	Payload:       "outgoing_events.payload",
	Topic:         "outgoing_events.topic",
	Status:        "outgoing_events.status",
	LastError:     "outgoing_events.last_error",
	CorrelationID: "outgoing_events.correlation_id",
	TraceID:       "outgoing_events.trace_id",
	SpanID:        "outgoing_events.span_id",
	RetryCount:    "outgoing_events.retry_count",
	CreatedAt:     "outgoing_events.created_at",
	UpdatedAt:     "outgoing_events.updated_at",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertypes_JSON struct{ field string }

func (w whereHelpertypes_JSON) EQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_JSON) NEQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_JSON) LT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_JSON) LTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_JSON) GT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_JSON) GTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpernull_String struct{ field string }

func (w whereHelpernull_String) EQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_String) NEQ(x null.String) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_String) LT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_String) LTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_String) GT(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_String) GTE(x null.String) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_String) LIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" LIKE ?", x)
}
func (w whereHelpernull_String) NLIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT LIKE ?", x)
}
func (w whereHelpernull_String) ILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" ILIKE ?", x)
}
func (w whereHelpernull_String) NILIKE(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT ILIKE ?", x)
}
func (w whereHelpernull_String) SIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" SIMILAR TO ?", x)
}
func (w whereHelpernull_String) NSIMILAR(x null.String) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelpernull_String) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_String) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_String) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_String) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelperint struct{ field string }

func (w whereHelperint) EQ(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint) NEQ(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint) LT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint) LTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint) GT(x int) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint) GTE(x int) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var OutgoingEventWhere = struct {
	ID            whereHelperint64
	Payload       whereHelpertypes_JSON
	Topic         whereHelperstring
	Status        whereHelperstring
	LastError     whereHelpernull_String
	CorrelationID whereHelperstring
	TraceID       whereHelperstring
	SpanID        whereHelperstring
	RetryCount    whereHelperint
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
}{
	ID:            whereHelperint64{field: "\"outgoing_events\".\"id\""},
	Payload:       whereHelpertypes_JSON{field: "\"outgoing_events\".\"payload\""},
	Topic:         whereHelperstring{field: "\"outgoing_events\".\"topic\""},
	Status:        whereHelperstring{field: "\"outgoing_events\".\"status\""},
	LastError:     whereHelpernull_String{field: "\"outgoing_events\".\"last_error\""},
	CorrelationID: whereHelperstring{field: "\"outgoing_events\".\"correlation_id\""},
	TraceID:       whereHelperstring{field: "\"outgoing_events\".\"trace_id\""},
	SpanID:        whereHelperstring{field: "\"outgoing_events\".\"span_id\""},
	RetryCount:    whereHelperint{field: "\"outgoing_events\".\"retry_count\""},
	CreatedAt:     whereHelpertime_Time{field: "\"outgoing_events\".\"created_at\""},
	UpdatedAt:     whereHelpertime_Time{field: "\"outgoing_events\".\"updated_at\""},
}

// OutgoingEventRels is where relationship names are stored.
var OutgoingEventRels = struct {
}{}

// outgoingEventR is where relationships are stored.
type outgoingEventR struct {
}

// NewStruct creates a new relationship struct
func (*outgoingEventR) NewStruct() *outgoingEventR {
	return &outgoingEventR{}
}

// outgoingEventL is where Load methods for each relationship are stored.
type outgoingEventL struct{}

var (
	outgoingEventAllColumns            = []string{"id", "payload", "topic", "status", "last_error", "correlation_id", "trace_id", "span_id", "retry_count", "created_at", "updated_at"}
	outgoingEventColumnsWithoutDefault = []string{"id", "payload", "topic", "correlation_id", "trace_id", "span_id"}
	outgoingEventColumnsWithDefault    = []string{"status", "last_error", "retry_count", "created_at", "updated_at"}
	outgoingEventPrimaryKeyColumns     = []string{"id"}
	outgoingEventGeneratedColumns      = []string{}
)

type (
	// OutgoingEventSlice is an alias for a slice of pointers to OutgoingEvent.
	// This should almost always be used instead of []OutgoingEvent.
	OutgoingEventSlice []*OutgoingEvent
	// OutgoingEventHook is the signature for custom OutgoingEvent hook methods
	OutgoingEventHook func(context.Context, boil.ContextExecutor, *OutgoingEvent) error

	outgoingEventQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	outgoingEventType                 = reflect.TypeOf(&OutgoingEvent{})
	outgoingEventMapping              = queries.MakeStructMapping(outgoingEventType)
	outgoingEventPrimaryKeyMapping, _ = queries.BindMapping(outgoingEventType, outgoingEventMapping, outgoingEventPrimaryKeyColumns)
	outgoingEventInsertCacheMut       sync.RWMutex
	outgoingEventInsertCache          = make(map[string]insertCache)
	outgoingEventUpdateCacheMut       sync.RWMutex
	outgoingEventUpdateCache          = make(map[string]updateCache)
	outgoingEventUpsertCacheMut       sync.RWMutex
	outgoingEventUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var outgoingEventAfterSelectMu sync.Mutex
var outgoingEventAfterSelectHooks []OutgoingEventHook

var outgoingEventBeforeInsertMu sync.Mutex
var outgoingEventBeforeInsertHooks []OutgoingEventHook
var outgoingEventAfterInsertMu sync.Mutex
var outgoingEventAfterInsertHooks []OutgoingEventHook

var outgoingEventBeforeUpdateMu sync.Mutex
var outgoingEventBeforeUpdateHooks []OutgoingEventHook
var outgoingEventAfterUpdateMu sync.Mutex
var outgoingEventAfterUpdateHooks []OutgoingEventHook

var outgoingEventBeforeDeleteMu sync.Mutex
var outgoingEventBeforeDeleteHooks []OutgoingEventHook
var outgoingEventAfterDeleteMu sync.Mutex
var outgoingEventAfterDeleteHooks []OutgoingEventHook

var outgoingEventBeforeUpsertMu sync.Mutex
var outgoingEventBeforeUpsertHooks []OutgoingEventHook
var outgoingEventAfterUpsertMu sync.Mutex
var outgoingEventAfterUpsertHooks []OutgoingEventHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *OutgoingEvent) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range outgoingEventAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *OutgoingEvent) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range outgoingEventBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *OutgoingEvent) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range outgoingEventAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *OutgoingEvent) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range outgoingEventBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *OutgoingEvent) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range outgoingEventAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *OutgoingEvent) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range outgoingEventBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *OutgoingEvent) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range outgoingEventAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *OutgoingEvent) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range outgoingEventBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *OutgoingEvent) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range outgoingEventAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddOutgoingEventHook registers your hook function for all future operations.
func AddOutgoingEventHook(hookPoint boil.HookPoint, outgoingEventHook OutgoingEventHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		outgoingEventAfterSelectMu.Lock()
		outgoingEventAfterSelectHooks = append(outgoingEventAfterSelectHooks, outgoingEventHook)
		outgoingEventAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		outgoingEventBeforeInsertMu.Lock()
		outgoingEventBeforeInsertHooks = append(outgoingEventBeforeInsertHooks, outgoingEventHook)
		outgoingEventBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		outgoingEventAfterInsertMu.Lock()
		outgoingEventAfterInsertHooks = append(outgoingEventAfterInsertHooks, outgoingEventHook)
		outgoingEventAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		outgoingEventBeforeUpdateMu.Lock()
		outgoingEventBeforeUpdateHooks = append(outgoingEventBeforeUpdateHooks, outgoingEventHook)
		outgoingEventBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		outgoingEventAfterUpdateMu.Lock()
		outgoingEventAfterUpdateHooks = append(outgoingEventAfterUpdateHooks, outgoingEventHook)
		outgoingEventAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		outgoingEventBeforeDeleteMu.Lock()
		outgoingEventBeforeDeleteHooks = append(outgoingEventBeforeDeleteHooks, outgoingEventHook)
		outgoingEventBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		outgoingEventAfterDeleteMu.Lock()
		outgoingEventAfterDeleteHooks = append(outgoingEventAfterDeleteHooks, outgoingEventHook)
		outgoingEventAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		outgoingEventBeforeUpsertMu.Lock()
		outgoingEventBeforeUpsertHooks = append(outgoingEventBeforeUpsertHooks, outgoingEventHook)
		outgoingEventBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		outgoingEventAfterUpsertMu.Lock()
		outgoingEventAfterUpsertHooks = append(outgoingEventAfterUpsertHooks, outgoingEventHook)
		outgoingEventAfterUpsertMu.Unlock()
	}
}

// One returns a single outgoingEvent record from the query.
func (q outgoingEventQuery) One(ctx context.Context, exec boil.ContextExecutor) (*OutgoingEvent, error) {
	o := &OutgoingEvent{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: failed to execute a one query for outgoing_events")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all OutgoingEvent records from the query.
func (q outgoingEventQuery) All(ctx context.Context, exec boil.ContextExecutor) (OutgoingEventSlice, error) {
	var o []*OutgoingEvent

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "orm: failed to assign all query results to OutgoingEvent slice")
	}

	if len(outgoingEventAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all OutgoingEvent records in the query.
func (q outgoingEventQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to count outgoing_events rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q outgoingEventQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "orm: failed to check if outgoing_events exists")
	}

	return count > 0, nil
}

// OutgoingEvents retrieves all the records using an executor.
func OutgoingEvents(mods ...qm.QueryMod) outgoingEventQuery {
	mods = append(mods, qm.From("\"outgoing_events\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"outgoing_events\".*"})
	}

	return outgoingEventQuery{q}
}

// FindOutgoingEvent retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindOutgoingEvent(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*OutgoingEvent, error) {
	outgoingEventObj := &OutgoingEvent{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"outgoing_events\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, outgoingEventObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: unable to select from outgoing_events")
	}

	if err = outgoingEventObj.doAfterSelectHooks(ctx, exec); err != nil {
		return outgoingEventObj, err
	}

	return outgoingEventObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *OutgoingEvent) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("orm: no outgoing_events provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(outgoingEventColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	outgoingEventInsertCacheMut.RLock()
	cache, cached := outgoingEventInsertCache[key]
	outgoingEventInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			outgoingEventAllColumns,
			outgoingEventColumnsWithDefault,
			outgoingEventColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(outgoingEventType, outgoingEventMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(outgoingEventType, outgoingEventMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"outgoing_events\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"outgoing_events\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "orm: unable to insert into outgoing_events")
	}

	if !cached {
		outgoingEventInsertCacheMut.Lock()
		outgoingEventInsertCache[key] = cache
		outgoingEventInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the OutgoingEvent.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *OutgoingEvent) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	outgoingEventUpdateCacheMut.RLock()
	cache, cached := outgoingEventUpdateCache[key]
	outgoingEventUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			outgoingEventAllColumns,
			outgoingEventPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("orm: unable to update outgoing_events, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"outgoing_events\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, outgoingEventPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(outgoingEventType, outgoingEventMapping, append(wl, outgoingEventPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update outgoing_events row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by update for outgoing_events")
	}

	if !cached {
		outgoingEventUpdateCacheMut.Lock()
		outgoingEventUpdateCache[key] = cache
		outgoingEventUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q outgoingEventQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all for outgoing_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected for outgoing_events")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o OutgoingEventSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("orm: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), outgoingEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"outgoing_events\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, outgoingEventPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all in outgoingEvent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected all in update all outgoingEvent")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *OutgoingEvent) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("orm: no outgoing_events provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(outgoingEventColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	outgoingEventUpsertCacheMut.RLock()
	cache, cached := outgoingEventUpsertCache[key]
	outgoingEventUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			outgoingEventAllColumns,
			outgoingEventColumnsWithDefault,
			outgoingEventColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			outgoingEventAllColumns,
			outgoingEventPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("orm: unable to upsert outgoing_events, could not build update column list")
		}

		ret := strmangle.SetComplement(outgoingEventAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(outgoingEventPrimaryKeyColumns) == 0 {
				return errors.New("orm: unable to upsert outgoing_events, could not build conflict column list")
			}

			conflict = make([]string, len(outgoingEventPrimaryKeyColumns))
			copy(conflict, outgoingEventPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"outgoing_events\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(outgoingEventType, outgoingEventMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(outgoingEventType, outgoingEventMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "orm: unable to upsert outgoing_events")
	}

	if !cached {
		outgoingEventUpsertCacheMut.Lock()
		outgoingEventUpsertCache[key] = cache
		outgoingEventUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single OutgoingEvent record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *OutgoingEvent) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("orm: no OutgoingEvent provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), outgoingEventPrimaryKeyMapping)
	sql := "DELETE FROM \"outgoing_events\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete from outgoing_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by delete for outgoing_events")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q outgoingEventQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("orm: no outgoingEventQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from outgoing_events")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for outgoing_events")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o OutgoingEventSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(outgoingEventBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), outgoingEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"outgoing_events\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, outgoingEventPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from outgoingEvent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for outgoing_events")
	}

	if len(outgoingEventAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *OutgoingEvent) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindOutgoingEvent(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OutgoingEventSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := OutgoingEventSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), outgoingEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"outgoing_events\".* FROM \"outgoing_events\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, outgoingEventPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "orm: unable to reload all in OutgoingEventSlice")
	}

	*o = slice

	return nil
}

// OutgoingEventExists checks if the OutgoingEvent row exists.
func OutgoingEventExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"outgoing_events\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "orm: unable to check if outgoing_events exists")
	}

	return exists, nil
}

// Exists checks if the OutgoingEvent row exists.
func (o *OutgoingEvent) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return OutgoingEventExists(ctx, exec, o.ID)
}
