// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ShortURL is an object representing the database table.
type ShortURL struct {
	ShortCode   string    `boil:"short_code" json:"short_code" toml:"short_code" yaml:"short_code"`
	OriginalURL string    `boil:"original_url" json:"original_url" toml:"original_url" yaml:"original_url"`
	Status      string    `boil:"status" json:"status" toml:"status" yaml:"status"`
	CreatedAt   time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *shortURLR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L shortURLL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ShortURLColumns = struct {
	ShortCode   string
	OriginalURL string
	Status      string
	CreatedAt   string
	UpdatedAt   string
}{
	ShortCode:   "short_code",
	OriginalURL: "original_url",
	Status:      "status",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

var ShortURLTableColumns = struct {
	ShortCode   string
	OriginalURL string
	Status      string
	CreatedAt   string
	UpdatedAt   string
}{
	ShortCode:   "short_urls.short_code",
	OriginalURL: "short_urls.original_url",
	Status:      "short_urls.status",
	CreatedAt:   "short_urls.created_at",
	UpdatedAt:   "short_urls.updated_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var ShortURLWhere = struct {
	ShortCode   whereHelperstring
	OriginalURL whereHelperstring
	Status      whereHelperstring
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpertime_Time
}{
	ShortCode:   whereHelperstring{field: "\"short_urls\".\"short_code\""},
	OriginalURL: whereHelperstring{field: "\"short_urls\".\"original_url\""},
	Status:      whereHelperstring{field: "\"short_urls\".\"status\""},
	CreatedAt:   whereHelpertime_Time{field: "\"short_urls\".\"created_at\""},
	UpdatedAt:   whereHelpertime_Time{field: "\"short_urls\".\"updated_at\""},
}

// ShortURLRels is where relationship names are stored.
var ShortURLRels = struct {
}{}

// shortURLR is where relationships are stored.
type shortURLR struct {
}

// NewStruct creates a new relationship struct
func (*shortURLR) NewStruct() *shortURLR {
	return &shortURLR{}
}

// shortURLL is where Load methods for each relationship are stored.
type shortURLL struct{}

var (
	shortURLAllColumns            = []string{"short_code", "original_url", "status", "created_at", "updated_at"}
	shortURLColumnsWithoutDefault = []string{"short_code", "original_url", "status"}
	shortURLColumnsWithDefault    = []string{"created_at", "updated_at"}
	shortURLPrimaryKeyColumns     = []string{"short_code"}
	shortURLGeneratedColumns      = []string{}
)

type (
	// ShortURLSlice is an alias for a slice of pointers to ShortURL.
	// This should almost always be used instead of []ShortURL.
	ShortURLSlice []*ShortURL
	// ShortURLHook is the signature for custom ShortURL hook methods
	ShortURLHook func(context.Context, boil.ContextExecutor, *ShortURL) error

	shortURLQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	shortURLType                 = reflect.TypeOf(&ShortURL{})
	shortURLMapping              = queries.MakeStructMapping(shortURLType)
	shortURLPrimaryKeyMapping, _ = queries.BindMapping(shortURLType, shortURLMapping, shortURLPrimaryKeyColumns)
	shortURLInsertCacheMut       sync.RWMutex
	shortURLInsertCache          = make(map[string]insertCache)
	shortURLUpdateCacheMut       sync.RWMutex
	shortURLUpdateCache          = make(map[string]updateCache)
	shortURLUpsertCacheMut       sync.RWMutex
	shortURLUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var shortURLAfterSelectMu sync.Mutex
var shortURLAfterSelectHooks []ShortURLHook

var shortURLBeforeInsertMu sync.Mutex
var shortURLBeforeInsertHooks []ShortURLHook
var shortURLAfterInsertMu sync.Mutex
var shortURLAfterInsertHooks []ShortURLHook

var shortURLBeforeUpdateMu sync.Mutex
var shortURLBeforeUpdateHooks []ShortURLHook
var shortURLAfterUpdateMu sync.Mutex
var shortURLAfterUpdateHooks []ShortURLHook

var shortURLBeforeDeleteMu sync.Mutex
var shortURLBeforeDeleteHooks []ShortURLHook
var shortURLAfterDeleteMu sync.Mutex
var shortURLAfterDeleteHooks []ShortURLHook

var shortURLBeforeUpsertMu sync.Mutex
var shortURLBeforeUpsertHooks []ShortURLHook
var shortURLAfterUpsertMu sync.Mutex
var shortURLAfterUpsertHooks []ShortURLHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *ShortURL) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shortURLAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *ShortURL) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shortURLBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *ShortURL) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shortURLAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *ShortURL) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shortURLBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *ShortURL) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shortURLAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *ShortURL) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shortURLBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *ShortURL) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shortURLAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *ShortURL) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shortURLBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *ShortURL) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range shortURLAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddShortURLHook registers your hook function for all future operations.
func AddShortURLHook(hookPoint boil.HookPoint, shortURLHook ShortURLHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		shortURLAfterSelectMu.Lock()
		shortURLAfterSelectHooks = append(shortURLAfterSelectHooks, shortURLHook)
		shortURLAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		shortURLBeforeInsertMu.Lock()
		shortURLBeforeInsertHooks = append(shortURLBeforeInsertHooks, shortURLHook)
		shortURLBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		shortURLAfterInsertMu.Lock()
		shortURLAfterInsertHooks = append(shortURLAfterInsertHooks, shortURLHook)
		shortURLAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		shortURLBeforeUpdateMu.Lock()
		shortURLBeforeUpdateHooks = append(shortURLBeforeUpdateHooks, shortURLHook)
		shortURLBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		shortURLAfterUpdateMu.Lock()
		shortURLAfterUpdateHooks = append(shortURLAfterUpdateHooks, shortURLHook)
		shortURLAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		shortURLBeforeDeleteMu.Lock()
		shortURLBeforeDeleteHooks = append(shortURLBeforeDeleteHooks, shortURLHook)
		shortURLBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		shortURLAfterDeleteMu.Lock()
		shortURLAfterDeleteHooks = append(shortURLAfterDeleteHooks, shortURLHook)
		shortURLAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		shortURLBeforeUpsertMu.Lock()
		shortURLBeforeUpsertHooks = append(shortURLBeforeUpsertHooks, shortURLHook)
		shortURLBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		shortURLAfterUpsertMu.Lock()
		shortURLAfterUpsertHooks = append(shortURLAfterUpsertHooks, shortURLHook)
		shortURLAfterUpsertMu.Unlock()
	}
}

// One returns a single shortURL record from the query.
func (q shortURLQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ShortURL, error) {
	o := &ShortURL{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: failed to execute a one query for short_urls")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all ShortURL records from the query.
func (q shortURLQuery) All(ctx context.Context, exec boil.ContextExecutor) (ShortURLSlice, error) {
	var o []*ShortURL

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "orm: failed to assign all query results to ShortURL slice")
	}

	if len(shortURLAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all ShortURL records in the query.
func (q shortURLQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to count short_urls rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q shortURLQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "orm: failed to check if short_urls exists")
	}

	return count > 0, nil
}

// ShortUrls retrieves all the records using an executor.
func ShortUrls(mods ...qm.QueryMod) shortURLQuery {
	mods = append(mods, qm.From("\"short_urls\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"short_urls\".*"})
	}

	return shortURLQuery{q}
}

// FindShortURL retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindShortURL(ctx context.Context, exec boil.ContextExecutor, shortCode string, selectCols ...string) (*ShortURL, error) {
	shortURLObj := &ShortURL{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"short_urls\" where \"short_code\"=$1", sel,
	)

	q := queries.Raw(query, shortCode)

	err := q.Bind(ctx, exec, shortURLObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "orm: unable to select from short_urls")
	}

	if err = shortURLObj.doAfterSelectHooks(ctx, exec); err != nil {
		return shortURLObj, err
	}

	return shortURLObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ShortURL) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("orm: no short_urls provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(shortURLColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	shortURLInsertCacheMut.RLock()
	cache, cached := shortURLInsertCache[key]
	shortURLInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			shortURLAllColumns,
			shortURLColumnsWithDefault,
			shortURLColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(shortURLType, shortURLMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(shortURLType, shortURLMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"short_urls\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"short_urls\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "orm: unable to insert into short_urls")
	}

	if !cached {
		shortURLInsertCacheMut.Lock()
		shortURLInsertCache[key] = cache
		shortURLInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the ShortURL.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ShortURL) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	shortURLUpdateCacheMut.RLock()
	cache, cached := shortURLUpdateCache[key]
	shortURLUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			shortURLAllColumns,
			shortURLPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("orm: unable to update short_urls, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"short_urls\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, shortURLPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(shortURLType, shortURLMapping, append(wl, shortURLPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update short_urls row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by update for short_urls")
	}

	if !cached {
		shortURLUpdateCacheMut.Lock()
		shortURLUpdateCache[key] = cache
		shortURLUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q shortURLQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all for short_urls")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected for short_urls")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ShortURLSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("orm: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), shortURLPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"short_urls\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, shortURLPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to update all in shortURL slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to retrieve rows affected all in update all shortURL")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ShortURL) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("orm: no short_urls provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(shortURLColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	shortURLUpsertCacheMut.RLock()
	cache, cached := shortURLUpsertCache[key]
	shortURLUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			shortURLAllColumns,
			shortURLColumnsWithDefault,
			shortURLColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			shortURLAllColumns,
			shortURLPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("orm: unable to upsert short_urls, could not build update column list")
		}

		ret := strmangle.SetComplement(shortURLAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(shortURLPrimaryKeyColumns) == 0 {
				return errors.New("orm: unable to upsert short_urls, could not build conflict column list")
			}

			conflict = make([]string, len(shortURLPrimaryKeyColumns))
			copy(conflict, shortURLPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"short_urls\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(shortURLType, shortURLMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(shortURLType, shortURLMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "orm: unable to upsert short_urls")
	}

	if !cached {
		shortURLUpsertCacheMut.Lock()
		shortURLUpsertCache[key] = cache
		shortURLUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single ShortURL record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ShortURL) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("orm: no ShortURL provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), shortURLPrimaryKeyMapping)
	sql := "DELETE FROM \"short_urls\" WHERE \"short_code\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete from short_urls")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by delete for short_urls")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q shortURLQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("orm: no shortURLQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from short_urls")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for short_urls")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ShortURLSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(shortURLBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), shortURLPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"short_urls\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, shortURLPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "orm: unable to delete all from shortURL slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "orm: failed to get rows affected by deleteall for short_urls")
	}

	if len(shortURLAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ShortURL) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindShortURL(ctx, exec, o.ShortCode)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ShortURLSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ShortURLSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), shortURLPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"short_urls\".* FROM \"short_urls\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, shortURLPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "orm: unable to reload all in ShortURLSlice")
	}

	*o = slice

	return nil
}

// ShortURLExists checks if the ShortURL row exists.
func ShortURLExists(ctx context.Context, exec boil.ContextExecutor, shortCode string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"short_urls\" where \"short_code\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, shortCode)
	}
	row := exec.QueryRowContext(ctx, sql, shortCode)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "orm: unable to check if short_urls exists")
	}

	return exists, nil
}

// Exists checks if the ShortURL row exists.
func (o *ShortURL) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ShortURLExists(ctx, exec, o.ShortCode)
}
