// Code generated by mockery v2.53.4. DO NOT EDIT.

package kafkaoutboxevent

import (
	context "context"

	model "github.com/kytruongdev/sturl/url-shortener-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// GetByStatus provides a mock function with given fields: ctx, status
func (_m *MockRepository) GetByStatus(ctx context.Context, status string) (model.KafkaOutboxEvent, error) {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for GetByStatus")
	}

	var r0 model.KafkaOutboxEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.KafkaOutboxEvent, error)); ok {
		return rf(ctx, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.KafkaOutboxEvent); ok {
		r0 = rf(ctx, status)
	} else {
		r0 = ret.Get(0).(model.KafkaOutboxEvent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *MockRepository) Insert(_a0 context.Context, _a1 model.KafkaOutboxEvent) (model.KafkaOutboxEvent, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 model.KafkaOutboxEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.KafkaOutboxEvent) (model.KafkaOutboxEvent, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.KafkaOutboxEvent) model.KafkaOutboxEvent); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.KafkaOutboxEvent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.KafkaOutboxEvent) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
