// Code generated by mockery v2.53.4. DO NOT EDIT.

package outgoingevent

import (
	context "context"

	model "github.com/kytruongdev/sturl/url-shortener-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

// GetByStatus provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockRepository) GetByStatus(_a0 context.Context, _a1 string, _a2 int) ([]model.OutgoingEvent, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetByStatus")
	}

	var r0 []model.OutgoingEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]model.OutgoingEvent, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []model.OutgoingEvent); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OutgoingEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingEventsToRetry provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockRepository) GetPendingEventsToRetry(_a0 context.Context, _a1 string, _a2 int) ([]model.OutgoingEvent, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingEventsToRetry")
	}

	var r0 []model.OutgoingEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]model.OutgoingEvent, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []model.OutgoingEvent); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OutgoingEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *MockRepository) Insert(_a0 context.Context, _a1 model.OutgoingEvent) (model.OutgoingEvent, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 model.OutgoingEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OutgoingEvent) (model.OutgoingEvent, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.OutgoingEvent) model.OutgoingEvent); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(model.OutgoingEvent)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.OutgoingEvent) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockRepository) Update(_a0 context.Context, _a1 model.OutgoingEvent, _a2 int64) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OutgoingEvent, int64) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
