// Code generated by mockery v2.53.4. DO NOT EDIT.

package repository

import (
	context "context"

	backoff "github.com/cenkalti/backoff/v4"

	kafkaoutboxevent "github.com/kytruongdev/sturl/url-shortener-service/internal/repository/kafkaoutboxevent"
	mock "github.com/stretchr/testify/mock"

	shorturl "github.com/kytruongdev/sturl/url-shortener-service/internal/repository/shorturl"
)

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

// DoInTx provides a mock function with given fields: ctx, backoffPolicy, fn
func (_m *MockRegistry) DoInTx(ctx context.Context, backoffPolicy backoff.BackOff, fn func(context.Context, Registry) error) error {
	ret := _m.Called(ctx, backoffPolicy, fn)

	if len(ret) == 0 {
		panic("no return value specified for DoInTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, backoff.BackOff, func(context.Context, Registry) error) error); ok {
		r0 = rf(ctx, backoffPolicy, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// KafkaOutboxEvent provides a mock function with no fields
func (_m *MockRegistry) KafkaOutboxEvent() kafkaoutboxevent.Repository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for KafkaOutboxEvent")
	}

	var r0 kafkaoutboxevent.Repository
	if rf, ok := ret.Get(0).(func() kafkaoutboxevent.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kafkaoutboxevent.Repository)
		}
	}

	return r0
}

// ShortUrl provides a mock function with no fields
func (_m *MockRegistry) ShortUrl() shorturl.Repository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShortUrl")
	}

	var r0 shorturl.Repository
	if rf, ok := ret.Get(0).(func() shorturl.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shorturl.Repository)
		}
	}

	return r0
}

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
